server:
  port: 8086
  
spring:
  eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://192.168.0.27:8761/eureka/
