server:
  port: 8086


resilience4j:
  circuitbreaker:
    instances:
      licenseService: 
        registerHealthIndicator: true 
        ringBufferSizeInClosedState: 5 
        ringBufferSizeInHalfOpenState: 3 
        waitDurationInOpenState: 10s 
        failureRateThreshold: 50 
        recordExceptions: 
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
  retry:
    instances:
      retryLicenseService:
        maxRetryAttempts: 5 
        waitDuration: 10000 
        retry-exceptions: 
        - java.util.concurrent.TimeoutException

spring:
  eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://192.168.0.27:8761/eureka/
        
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
